dbt-etl:
  outputs:
    dev:
      dataset: cleaned
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: ./dbt-bigquery-key.json
      location: US
      method: service-account
      priority: interactive
      project: dm-09242024
      threads: 1
      type: bigquery
  target: dev